name: CI/CD MLOps PF

on:
  push:
    branches:
      - dev
      - prod
  pull_request:
    branches:
      - dev
      - prod

jobs:
  test:
    name: Test FastAPI recommender
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          USE_FAKE_MODEL: "true"
          APP_ENV: "test"
        run: |
          pytest -v
